name: Scheduled Tasks

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  weekly-routines:
    runs-on: ubuntu-24.04
    env:
      RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
      RAPID_API_HOST: ${{ secrets.RAPID_API_HOST }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          cache: 'pnpm'
          node-version-file: '.tool-versions'

      - name: Install dependencies
        run: pnpm install

      - name: Calculate NFL week number
        id: calc
        run: |
          start_date="2025-09-04"
          now=$(date +%s)
          start=$(perl -MTime::Piece -e "print Time::Piece->strptime('$start_date', '%Y-%m-%d')->epoch")
          diff_days=$(( (now - start) / 86400 ))

          if [ $diff_days -lt 0 ]; then
            echo "week_number=0" >> $GITHUB_ENV
            echo "[INFO] Season hasn't started yet (diff_days=$diff_days)"
            exit 0
          fi

          week_number=$(( diff_days / 7 + 1 ))
          echo "week_number=$week_number" >> $GITHUB_ENV
          echo "[INFO] Calculated week_number=$week_number"

      - name: Daily Update
        run: |
          day=$(date +%u)
          if [ "$day" -eq 3 ] || [ "$day" -eq 4 ]; then
            echo "[SKIP] Daily Update — not run on Wed/Thu (day=$day)"
            exit 0
          fi
          if [ "$week_number" -eq 0 ]; then
            echo "[SKIP] Daily Update — season not started yet"
            exit 0
          fi
          if [ "$week_number" -ge 19 ]; then
            echo "[SKIP] Daily Update — season complete (week=$week_number)"
            exit 0
          fi

          echo "[RUN] Daily Update — week $week_number, year 2025"
          pnpm cli:prod daily-update --week $week_number --year 2025

      - name: Finalize Week
        run: |
          day=$(date +%u)
          if [ "$day" -ne 2 ]; then
            echo "[SKIP] Finalize Week — today is not Tuesday (day=$day)"
            exit 0
          fi
          if [ "$week_number" -eq 0 ]; then
            echo "[SKIP] Finalize Week — season not started yet"
            exit 0
          fi
          if [ "$week_number" -ge 19 ]; then
            echo "[SKIP] Finalize Week — season complete (week=$week_number)"
            exit 0
          fi

          echo "[RUN] Finalize Week — week $week_number, year 2025"
          pnpm cli:prod complete-week --week $week_number --year 2025

      - name: Prepare Next Week
        run: |
          day=$(date +%u)
          if [ "$day" -ne 2 ]; then
            echo "[SKIP] Prepare Next Week — today is not Tuesday (day=$day)"
            exit 0
          fi
          if [ "$week_number" -eq 0 ]; then
            echo "[SKIP] Prepare Next Week — season not started yet"
            exit 0
          fi
          if [ "$week_number" -ge 18 ]; then
            echo "[SKIP] Prepare Next Week — no week after $week_number"
            exit 0
          fi

          next_week=$(( week_number + 1 ))
          echo "[RUN] Prepare Next Week — week $next_week, year 2025"
          pnpm cli:prod prepare-week --week $next_week --year 2025
