name: Setup Betting

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * 2' # Run every Tuesday at 17 UTC (12pm ET, 11am CT)

jobs:
  setup-betting:
    runs-on: ubuntu-24.04
    env:
      RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
      RAPID_API_HOST: ${{ secrets.RAPID_API_HOST }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version-file: '.tool-versions'

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Calculate NFL week number
        id: calc
        run: |
          start_date="2025-09-04"
          now=$(date +%s)
          start=$(perl -MTime::Piece -e "print Time::Piece->strptime('$start_date', '%Y-%m-%d')->epoch")
          diff_days=$(( (now - start) / 86400 ))

          if [ $diff_days -lt 0 ]; then
            echo "week_number=0" >> $GITHUB_ENV
            echo "[INFO] Season hasn't started yet (diff_days=$diff_days)"
            exit 0
          fi

          week_number=$(( diff_days / 7 + 1 ))
          echo "week_number=$week_number" >> $GITHUB_ENV
          echo "[INFO] Calculated week_number=$week_number"

      - name: Setup Betting
        run: |
          if [ "$week_number" -eq 0 ]; then
            echo "[SKIP] Setup Betting — season not started yet"
            exit 0
          fi
          if [ "$week_number" -ge 18 ]; then
            echo "[SKIP] Setup Betting — no week after $week_number"
            exit 0
          fi

          next_week=$(( week_number + 1 ))
          echo "[RUN] Setup Betting — week $next_week, year 2025"
          pnpm start setup-betting --week=$next_week --year=2025
